package com.ethosa.wakatime.models;

public class WakatimeUserData {
    public String bio;
    public String color_scheme;
    public String created_at;
    public String date_format;
    public String default_dashboard_range;
    public String display_name;
    public String durations_slice_by;
    public String email;
    public String full_name;
    public String human_readable_website;
    public String id;
    public String last_heartbeat_at;
    public String last_plugin;
    public String last_plugin_name;
    public String last_project;
    public String location;
    public String modified_at;
    public String photo;
    public String plan;
    public String profile_url;
    public String profile_url_escaped;
    public String public_email;
    public String public_profile_time_range;
    public String time_format_display;
    public String timezone;
    public String username;
    public String website;
    public int timeout;
    public int weekday_start;
    public boolean has_premium_features;
    public boolean is_email_confirmed;
    public boolean is_email_public;
    public boolean is_hireable;
    public boolean is_onboarding_finished;
    public boolean languages_used_public;
    public boolean logged_time_public;
    public boolean needs_payment_method;
    public boolean photo_public;
    public boolean show_machine_name_ip;
    public boolean time_format_24hr;
    public boolean writes_only;
}
